BASIC NUMPY IN PYTHON:

In [1]:
import numpy as np
arr=np.array([0,1,2,3,4,5])
print(type(arr))

<class 'numpy.ndarray'>


NUMPY 1D ARRAY :

In [3]:
import numpy as np
a=np.array([7,8,9])
print(a)
print(a.ndim)
print(a.shape)

[7 8 9]
1
(3,)


In [5]:
#2-DIMENSIONAL ARRAY:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
print(b.ndim)          
print(b.shape)         


[[1 2 3]
 [4 5 6]]
2
(2, 3)


BASIC OPERATIONS :

In [6]:
import numpy as np
arr1=np.array([0,1,2])
arr2=np.array([3,4,5])
print(arr1+arr2)
print(arr1 * arr2 )


[3 5 7]
[ 0  4 10]


NumPy arrays are preferred for numerical computations due to speed and convenience

In [7]:
# Python list
lst = [1, 2, 3]
print([x * 2 for x in lst])  # [2, 4, 6]

# NumPy array
arr = np.array([1, 2, 3])
print(arr * 2)               # [2 4 6]


[2, 4, 6]
[2 4 6]


SPECIAL DATATYPE: 
DTYPE :OBJECT

In [8]:
arr = np.array([1, 'a', 3.5], dtype=object)
print(arr)
print(arr.dtype) 


[1 'a' 3.5]
object


In [ ]:
#dtype :TELLS US WHAT TYPE OF DATATYPE DO WE NEED IN ARRAY 
arr3 = np.array([1, 2, 3], dtype=float)
print(arr3)

[1. 2. 3.]


np.arange():

In [10]:
import numpy as np

arr = np.arange(0, 10, 2)
print(arr)
# Output: [0 2 4 6 8]

arr_float = np.arange(0, 1, 0.2)
print(arr_float)
# Output: [0.  0.2 0.4 0.6 0.8]


[0 2 4 6 8]
[0.  0.2 0.4 0.6 0.8]


np.zeros():

In [11]:
import numpy as np

# 1D array of zeros with length 5
zeros_1d = np.zeros(5)
print(zeros_1d)
# Output: [0. 0. 0. 0. 0.]

# 2D array of zeros with shape 3x4
zeros_2d = np.zeros((3, 4), dtype=int)
print(zeros_2d)
# Output:
# [[0 0 0 0]
#  [0 0 0 0]
#  [0 0 0 0]]


[0. 0. 0. 0. 0.]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [12]:
import numpy as np

# Generate 7 evenly spaced numbers between 3.0 and 4.0 (inclusive)
arr1 = np.linspace(3.0, 4.0, 7)
print(arr1)
# Output: [3.         3.16666667 3.33333333 3.5        3.66666667 3.83333333 4.        ]

# Exclude the endpoint
arr2 = np.linspace(3.0, 4.0, 7, endpoint=False)
print(arr2)
# Output: [3.         3.14285714 3.28571429 3.42857143 3.57142857 3.71428571 3.85714286]

# Return the step size between samples
arr3, step = np.linspace(0, 10, 5, retstep=True)
print(arr3)
print("Step size:", step)
# Output:
# [ 0.   2.5  5.   7.5 10. ]
# Step size: 2.5


[3.         3.16666667 3.33333333 3.5        3.66666667 3.83333333
 4.        ]
[3.         3.14285714 3.28571429 3.42857143 3.57142857 3.71428571
 3.85714286]
[ 0.   2.5  5.   7.5 10. ]
Step size: 2.5


In [13]:
# 10 points between 0 and 1 inclusive
points = np.linspace(0, 1, 10)
print(points)


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


numpy.eye():

In [14]:
import numpy as np

# 3x3 identity matrix
I = np.eye(3)
print(I)
# Output:
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]]

# 3x4 matrix with ones on main diagonal
I2 = np.eye(3, 4)
print(I2)
# Output:
# [[1. 0. 0. 0.]
#  [0. 1. 0. 0.]
#  [0. 0. 1. 0.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [15]:
import numpy as np

# Create an empty 2x3 array of floats (uninitialized values)
empty_arr = np.empty((2, 3))
print(empty_arr)


[[0.0e+000 4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323 2.5e-323]]


In [16]:
import numpy as np

vector = np.array([1, 2, 3, 4, 5])
print(vector)
print("Shape:", vector.shape)  # (5,)
print("Dimensions:", vector.ndim)  # 1


[1 2 3 4 5]
Shape: (5,)
Dimensions: 1


In [18]:
import numpy as np

# List of tuples (records)
data = [
    (1, 'Alice', 25.5),
    (2, 'Bob', 30.0),
    (3, 'Charlie', 22.0)
]

# Define structured dtype: id (int), name (string), score (float)
dtype = [('id', 'i4'), ('name', 'U10'), ('score', 'f4')]

arr = np.rec.fromrecords(data, dtype=dtype)
print(arr)

# Access a field
print(arr['name'])


[(1, 'Alice', 25.5) (2, 'Bob', 30. ) (3, 'Charlie', 22. )]
['Alice' 'Bob' 'Charlie']


VIEW WITH THE HELP OF SLICING :

In [19]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
slice_view = arr[1:4]  # This is a view

print("Original array:", arr)
print("Slice view:", slice_view)

# Modify view
slice_view[0] = 20

print("After modifying view:")
print("Original array:", arr)      # arr[1] changes to 20
print("Slice view:", slice_view)


Original array: [1 2 3 4 5]
Slice view: [2 3 4]
After modifying view:
Original array: [ 1 20  3  4  5]
Slice view: [20  3  4]


INDEXING IN NUMPY :

In [20]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])    # 10
print(arr[-1])   # 50 (last element)
print(arr[1:4])  # [20 30 40]


10
50
[20 30 40]


In [21]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print(arr2d[0, 1])  # 2 (row 0, column 1)
print(arr2d[1])     # [4 5 6] (row 1)


2
[4 5 6]


In [22]:
arr = np.array([10, 20, 30, 40, 50])
mask = arr > 25
print(mask)          # [False False  True  True  True]
print(arr[mask])     # [30 40 50]

# Or directly:
print(arr[arr > 25]) # [30 40 50]


[False False  True  True  True]
[30 40 50]
[30 40 50]


In [26]:
import numpy as np
rows,cols=3,3
indices=np.tril_indices(rows,k=0,m=cols)
print(indices)


(array([0, 1, 1, 2, 2, 2]), array([0, 0, 1, 0, 1, 2]))


ITERATION FOR 1D:

In [28]:
import numpy as np
arr=np.array([0,1,2])
for x in arr :
    print(x)


0
1
2


ITERATION FOR 2D:

In [29]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
for row in arr2d:
    print(row)
# Output: [1 2 3]
#         [4 5 6]


[1 2 3]
[4 5 6]


In [31]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
for row in arr2d:
    for x in row:
        print(x)

1
2
3
4
5
6


In [32]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in np.nditer(arr):
    print(x)
# Output: 1 2 3 4 5 6


1
2
3
4
5
6


In [33]:
arr = np.array([[1, 2], [3, 4]])
for x in np.nditer(arr, order='C'):
    print(x)
# Output: 1 2 3 4



1
2
3
4


In [34]:
for x in np.nditer(arr,order='F'):
    print(x)

1
3
2
4


In [37]:
for x in np.nditer(arr,op_flags=['readwrite']):
    x[...]=x*2
    print(x)

2
4
6
8


EXTERNAL LOOP:

In [38]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for row in np.nditer(arr, flags=['external_loop']):
    print(row)
# Output: [1 2 3]
#         [4 5 6]


[1 2 3 4 5 6]


3D ARRAY WITH EXTERNAL LOOP :

In [43]:
arr3d = np.arange(24).reshape((2, 3, 4))
print("Original array shape:", arr3d.shape)
print(arr3d)

for block in np.nditer(arr3d, flags=['external_loop']):
    print(block)


Original array shape: (2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


BROADCASTING ITERATION:

In [44]:
a = np.array([1, 2, 3])
b = np.array([[10], [20], [30]])

for x, y in np.nditer([a, b]):
    print(x, y)
# Output: (1,10) (2,10) (3,10) (1,20) (2,20) (3,20) (1,30) (2,30) (3,30)


1 10
2 10
3 10
1 20
2 20
3 20
1 30
2 30
3 30


NDEMURATE : INDEX AND VALUE 

In [45]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
for idx, val in np.ndenumerate(arr):
    print("Index:", idx, "Value:", val)
# Output: Index: (0, 0) Value: 1, etc.


Index: (0, 0) Value: 1
Index: (0, 1) Value: 2
Index: (0, 2) Value: 3
Index: (1, 0) Value: 4
Index: (1, 1) Value: 5
Index: (1, 2) Value: 6


BASIC BROADCASTING:

In [46]:
import numpy as np

arr = np.array([1, 2, 3])
result = arr + 5
print(result)  # [6 7 8]


[6 7 8]


2D ARRAYS WITH DIFF SHAPE :

In [47]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([[10], [20]])
result = a + b
print(result)
# [[11 12 13]
#  [24 25 26]]


[[11 12 13]
 [24 25 26]]


STATISTICAL OPERATIONS :

In [48]:
arr = np.array([1, 2, 3, 4, 5])
mean_val = np.mean(arr)  # 3.0
sum_val = np.sum(arr)    # 15
max_val = np.max(arr)    # 5


FOR 2D ARRAY : SPECIFY IF 0 FOR AXIS THEN COLOUMN SUM AND 1 FOR AXIS THEN ROW SUM:

In [49]:
arr2d = np.array([[1, 2], [3, 4]])
print(np.sum(arr2d, axis=0))  # [4 6] (column-wise sum)
print(np.sum(arr2d, axis=1))  # [3 7] (row-wise sum)


[4 6]
[3 7]


1D ARRAY INNER PDT :

In [50]:
import numpy as np

a = np.array([5, 10, 15])
b = np.array([20, 25, 30])

result = np.inner(a, b)
print(result)  # Output: 800


800


HIGHER DIMENSIONAL ARRAY : IT TAKE LAST DIMENSION OF 1ST ARRAY AND LAST DIMENSION OF THE 2ND ARRAY :

In [ ]:
x = np.arange(24).reshape((2, 3, 4))
y = np.arange(4)

result = np.inner(x, y)
print(result.shape)  # (2, 3)
print(result)
#EXACTLY THIS IS HAPPENING HERE :
# x[0,0,:] = [0, 1, 2, 3]
# y = [0, 1, 2, 3]

# inner = 0*0 + 1*1 + 2*2 + 3*3 = 0 + 1 + 4 + 9 = 14


(2, 3)
[[ 14  38  62]
 [ 86 110 134]]


MEAN,MEAN DEVIATION AND ABSOLUTE DEVIATION :

In [52]:
arr = np.array([1, 2, 3, 4, 5])

mean = np.mean(arr)
abs_deviation = np.abs(arr - mean)
mean_deviation = np.mean(abs_deviation)

print("Mean:", mean)                   # 3.0
print("Absolute deviations:", abs_deviation)  # [2. 1. 0. 1. 2.]
print("Mean deviation:", mean_deviation)      # 1.2


Mean: 3.0
Absolute deviations: [2. 1. 0. 1. 2.]
Mean deviation: 1.2


appending values :

In [53]:
a = np.array([1, 2, 3])
b = np.append(a, [4, 5])
print(b)  # [1 2 3 4 5]


[1 2 3 4 5]


swapping coloumns in a 2d array :

In [54]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
# Swap columns 0 and 2
a[:, [0, 2]] = a[:, [2, 0]]
print(a)
# [[3 2 1]
#  [6 5 4]]


[[3 2 1]
 [6 5 4]]


INSERTING NEW ARRAY IN AXIS :

In [55]:
a = np.array([1, 2, 3])
print(a.shape)         # (3,)

# Make it a column vector
b = a[:, np.newaxis]
print(b)
# [[1]
#  [2]
#  [3]]
print(b.shape)         # (3, 1)

# Make it a row vector
c = a[np.newaxis, :]
print(c)
# [[1 2 3]]
print(c.shape)         # (1, 3)


(3,)
[[1]
 [2]
 [3]]
(3, 1)
[[1 2 3]]
(1, 3)


STACKING ARRAY :

In [56]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Vertical stack (as rows)
v = np.vstack((a, b))
print(v)
# [[1 2 3]
#  [4 5 6]]

# Horizontal stack (as one row)
h = np.hstack((a, b))
print(h)
# [1 2 3 4 5 6]


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


CONCATENATIG ARRAY:

In [57]:
import numpy as np

a = np.ma.array([1, 2, 3])
b = np.ma.array([4, 5, 6])
c = np.ma.concatenate([a, b])
print(c)  # [1 2 3 4 5 6]


[1 2 3 4 5 6]


COMBINED ARRAY INDEX BY INDEX

In [58]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr[1, 2])  # 6 (row 1, column 2)


6


SPLITTING ARRAY :

In [59]:
arr = np.array([1, 2, 3, 4, 5, 6])
# Equal splits
print(np.split(arr, 3))  # [array([1,2]), array([3,4]), array([5,6])]

# Unequal splits
print(np.array_split(arr, 4))  # [array([1,2]), array([3,4]), array([5]), array([6])]


[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3, 4]), array([5]), array([6])]


COMPARING 2 NUMPY ARRAYS :

In [60]:
a = np.array([1, 2, 3])
b = np.array([1, 4, 3])
print(a == b)  # [True False True]
print(np.array_equal(a, b))  # False (checks if arrays are exactly the same)


[ True False  True]
False
